### ISSUE TITLE
UCL-ARC's big plan to reconcile with the upstream repo

### ISSUE THREAD

**Issue by dpshelio** [UCL-ARC/hpc-intro#34]
# Tasks
- [x] PR for our updates to the UCL-ARC site snippets
- [x] PRs for our contributions to the lessons
    - [x] Filezilla
      - [x] [branch](https://github.com/UCL-ARC/hpc-intro/tree/filezilla)
      - [x] [PR](https://github.com/carpentries-incubator/hpc-intro/pull/453)
    - [x] Rsync
      - [x] [branch](https://github.com/UCL-ARC/hpc-intro/tree/rsync)
      - [x] [PR](https://github.com/carpentries-incubator/hpc-intro/pull/454)

# local

24210cd 97e10c5 + f63ad48 (image) 553012e (config) 601a9ea (config)

# local snippets

3db7d9a b5820cf + cb95722 ca65da5 + 95797a1 (parallel) a6736d4 (typos)

## connecting myriad

trying to see whether we can keep them on the path e4a23cc 955eb1d

# Contributions

## time format

But suggested to go into snippets 4832a68

## rsync / copy files

15f692e 35a317e bb2d111 - deleted file can\'t pick.

## filezilla :heavy_check_mark: 

0baf804 (to add manually to transferring files) ~~c54fb6a~~

## Other

03d5ba9 (readme)

# don\'t care

02fdaf9

## Circle preview

8edc8f0 606c25e

# Careful merges

253d713 (big merge) d65a369 (#30)

# episode removed / leson changed revisit

## mpi python

ee55b56 ba8e5b2 f63ad48 + 4eeda6b + cc3763a + 668ed4b + (older one)

**Comment by cdkharris** [comment]
David and I met on 20240723 to talk about how we want to structure the repo and how we want to contribute going forward. The goals right now are to get the 'big merge' that I did in place, and simultaneously to get the repo set up such that we can send our contributions to the lessons, and our updates to the site snippets, upstream.

This issue details how each of the commits that went into the big merge (PR #31 ) should be sorted into:

- local changes like configuration for the website (should be pushed to the gh-pages branch but don't need to be merged back upstream)
- changes that we made to our site snippets (should be grouped together and sent upstream as a PR)
- contributions to the lessons (should be grouped into smaller PRs and sent upstream)
- changes to the MPI python lesson (which we don't need to worry about- this lesson has been so thoroughly overhauled that we should just take the upstream lesson and update our site snippets for SGE afterward)

**Comment by cdkharris** [comment]
Where commits are listed, they are listed in reverse chronological order- that is for rsync, 15f happened after 13a and bb2 was made first. This may be important if one wants to use `git cherry-pick`.

**Comment by cdkharris** [comment]
# The future of this repo

We currently have these three branches:

1. gh-pages (effectively, prod)
2. gh-pages-upstream (tracks the upstream repo)
3. cdkharris/big-merge (merged upstream with prod as-of ~2 months ago)

The goal is to have:

1. gh-pages (prod; upstream + our website configuration + "previews" of our contributions)
2. gh-pages-upstream (tracks the upstream repo)
3. Branches off of gh-pages-upstream (that will become PRs either for our site snippets or lesson contributions)

The plan to get from the current to the desired state is:

- [X] gh-pages-upstream
- [x] Merge cdkharris/big-merge into gh-pages (this will bring our "prod" much more closely in line with the upstream) #32
- [x] break up cdkharris/big-merge into component branches (see above)
- [x] Make PRs with those branches against the upstream
- [ ] periodically merge the upstream into gh-pages-upstream #33 
- [ ] periodically merge gh-pages-upstream into gh-pages

@dpshelio do you agree?

**Comment by cdkharris** [comment]
Closed with #31 - there are differences remaining but they are not complex differences and there are major changes planned for the future of the lesson, so this is managable.
